// src/frontend-react/src/CholeraStats.jsx
import { useState, useEffect } from "react";

const BASE_API = "/api/v1/cholera-stats";

const ESTADOS = {
  200: " - OK: La operación fue un éxito",
  201: " - Created: Creado correctamente",
  400: " - Bad Request: Campos incorrectos o incompletos",
  404: " - Not Found: El recurso no existe",
  405: " - Method Not Allowed: No puedes realizar esa operación",
  409: " - Conflict: Ya existe en la base de datos",
  500: " - Internal Server Error: Error interno en el servidor",
};

const EMPTY = {
  country: "", year: "",
  reportedCases: 0, reportedDeaths: 0,
  fatalityRate: 0, whoRegion: ""
};

const LIMIT = 10;

export default function CholeraStats() {
  const [datos, setDatos] = useState([]);
  const [status, setStatus] = useState(null);
  const [newRow, setNewRow] = useState(EMPTY);
  const [page, setPage] = useState(0);

  async function getDatos(p = page) {
    const res = await fetch(`${BASE_API}?limit=${LIMIT}&offset=${LIMIT * p}`);
    setDatos(await res.json());
  }

  useEffect(() => { getDatos(); }, [page]);

  async function loadInitial() {
    const res = await fetch(BASE_API + "/loadInitialData");
    setStatus(res.status);
    if (res.ok) getDatos();
  }

  async function add() {
    if (!newRow.country || !newRow.year || !newRow.whoRegion) {
      setStatus(400); return;
    }
    const res = await fetch(BASE_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(newRow),
    });
    setStatus(res.status);
    if (res.status === 201) { setNewRow(EMPTY); getDatos(); }
  }

  async function del(country, year) {
    if (!confirm("¿Borrar este registro?")) return;
    const res = await fetch(`${BASE_API}/${country}/${year}`, { method: "DELETE" });
    setStatus(res.status);
    if (res.ok) getDatos();
  }

  async function delAll() {
    if (!confirm("¿Borrar TODOS los registros?")) return;
    const res = await fetch(BASE_API, { method: "DELETE" });
    setStatus(res.status);
    if (res.ok) { setPage(0); getDatos(0); }
  }

  const set = (field) => (e) =>
    setNewRow((prev) => ({ ...prev, [field]: e.target.value }));

  return (
    <div style={{ padding: 16, fontFamily: "sans-serif" }}>
      <h1>Estadísticas del Cólera</h1>
      <button onClick={loadInitial}>Cargar datos iniciales</button>{" "}
      <button onClick={delAll}>Borrar todo</button>

      <hr />

      <table border="1" cellPadding="4" style={{ borderCollapse: "collapse", width: "100%" }}>
        <thead>
          <tr>
            <th>País</th><th>Año</th><th>Casos</th>
            <th>Muertes</th><th>Fatalidad</th><th>Región WHO</th>
            <th>Acción</th>
          </tr>
        </thead>
        <tbody>
          {datos.map((d) => (
            <tr key={d.country + d.year} data-testid="choleraRow">
              <td>{d.country}</td>
              <td>{d.year}</td>
              <td>{d.reportedCases}</td>
              <td>{d.reportedDeaths}</td>
              <td>{d.fatalityRate}</td>
              <td>{d.whoRegion}</td>
              <td>
                <button onClick={() => del(d.country, d.year)}>Borrar</button>{" "}
                <button onClick={() => window.location.href = `/react/${d.country}/${d.year}`}>Editar</button>
              </td>
            </tr>
          ))}

          <tr>
            <td><input data-testid="countryInput" value={newRow.country} onChange={set("country")} placeholder="País" /></td>
            <td><input data-testid="yearInput" type="number" value={newRow.year} onChange={set("year")} placeholder="Año" /></td>
            <td><input data-testid="reportedCasesInput" type="number" value={newRow.reportedCases} onChange={set("reportedCases")} /></td>
            <td><input data-testid="reportedDeathsInput" type="number" value={newRow.reportedDeaths} onChange={set("reportedDeaths")} /></td>
            <td><input data-testid="fatalityRateInput" type="number" step="0.01" value={newRow.fatalityRate} onChange={set("fatalityRate")} /></td>
            <td><input data-testid="regionInput" value={newRow.whoRegion} onChange={set("whoRegion")} placeholder="Región" /></td>
            <td><button onClick={add}>+ Añadir</button></td>
          </tr>
        </tbody>
      </table>

      <p>
        <button onClick={() => setPage((p) => Math.max(0, p - 1))} disabled={page === 0}>← Anterior</button>{" "}
        Página {page + 1}{" "}
        <button onClick={() => setPage((p) => p + 1)} disabled={datos.length < LIMIT}>Siguiente →</button>
      </p>

      <hr />
      <h2>Códigos de estado</h2>
      {status && <p><strong>Último resultado:</strong> {ESTADOS[status] ?? `${status} - Respuesta desconocida`}</p>}
    </div>
  );
}

// src/frontend/src/routes/cholera-stats/+page.svelte
<script>

import { dev } from '$app/environment';
import {onMount} from 'svelte';
// @ts-ignore
let cholera_stats=  $state([]);
let resultStatus = $state(0);
let newCountry = $state('PaisEjemplo');
let newYear = $state('1000');
let newReportedCases = $state('0');
let newReportedDeaths = $state('0');
let newFatalityRates = $state('0.0');
let newWhoRegion = $state('RegionEjemplo');
let filterCountry = $state('');
let filterYear = $state('');
let filterRegion = $state('');
let filterReportedCases = $state('');
let filterReportedDeaths = $state('');
let filterFatalityRate = $state('');
let filterFrom = $state('');
let filterTo = $state('');
let filterOffset=$state(0)  ;
let API = "/api/v1/cholera-stats";

if (dev)
    API = "http://localhost:3000"+API;

    // @ts-ignore
    async function getCholeraStats()  {
        let url = API + '?';
    
        if(filterCountry) url += `country=${filterCountry}&`;
        if(filterYear) url += `year=${filterYear}&`;
        if(filterRegion) url += `region=${filterRegion}&`;
        if(filterReportedCases) url += `reportedCases=${filterReportedCases}&`;
        if(filterReportedDeaths) url += `reportedDeaths=${filterReportedDeaths}&`;
        if(filterFatalityRate) url += `fatalityRate=${filterFatalityRate}&`;
        if(filterFrom) url += `from=${filterFrom}&`;
        if(filterTo) url += `to=${filterTo}&`;
        url += `offset=${filterOffset}&`;
        url += `limit=${LIMIT}&`;
        const res = await fetch(url, {method: "GET"});
        const data = await res.json();
        cholera_stats=data;
    }

     async function getInitdata()  {    
        const res = await fetch(API + '/loadInitialData', {method: "GET"});
        resultStatus = await res.status;
        if(resultStatus == 201 || resultStatus == 409)
            getCholeraStats();
    }


    // @ts-ignore
    async function deleteCholeraStat(country, year){
        const res = await fetch(API+'/'+country+'/'+year, {method : "DELETE"});
        resultStatus = await res.status
        if (resultStatus == 200)
            getCholeraStats();
    }



    // @ts-ignore
    async function deleteCholeraStats(){
        const res = await fetch(API, {method : "DELETE"});
        resultStatus = await res.status
        if (resultStatus == 200)
            getCholeraStats();
    }


    // @ts-ignore
    async function InsertCholeraStat(){
        let newCholeraStat= {
            country: newCountry,
            year: newYear,
            reportedCases: newReportedCases,
            reportedDeaths: newReportedDeaths,
            fatalityRate: newFatalityRates,
            whoRegion: newWhoRegion
        }
        const res = await fetch(API, 
        {method : "POST", 
        headers: {
            "Content-Type" : "application/json"
        },
        body: JSON.stringify(newCholeraStat)
        });
        resultStatus = await     res.status
        if (resultStatus == 201)
            getCholeraStats();
        
    }


    // @ts-ignore
    async function UpdateCholeraStat(country, year){
        let newCholeraStat= {
            country: newCountry,
            year: newYear,
            reportedCases: newReportedCases,
            reportedDeaths: newReportedDeaths,
            fatalityRate: newFatalityRates,
            whoRegion: newWhoRegion
        }
        const res = await fetch(API+'/'+country+'/'+year, 
        {method : "UPDATE", 
        headers: {
            "Content-Type" : "application/json"
        },
        body: JSON.stringify(newCholeraStat)
        });
        resultStatus = await res.status
        if (resultStatus == 201)
            getCholeraStats();
        
    }



    onMount(async () =>  {getCholeraStats(); }); //que se carga al iniciar la pagina


    const LIMIT = 10;

    async function incrementaOffset(){
        filterOffset += LIMIT;
        getCholeraStats();
    }

    async function decrementaOffset(){
        if(filterOffset >= LIMIT) filterOffset -= LIMIT;
        getCholeraStats();
    }

</script>

<svelte:head>
  <title>Cholera Stats</title>
</svelte:head>

<h1>Estadísticas del cólera</h1>  



{#if resultStatus == 200 || resultStatus == 201}
<div class="alert success">
  <strong>EXITO</strong> — Operación realizada con éxito
</div>
{/if}
{#if resultStatus == 400}
<div class="alert error">
  <strong>ERROR</strong> — Campos sin rellenar
</div>
{/if}
{#if resultStatus == 409}
<div class="alert error">
  <strong>ERROR</strong> — La estadística ya existe
</div>
{/if}


<style>
  .alert {
    padding: 10px 16px;
    border-radius: 6px;
    margin: 10px 0;
  }
  .success {
    background-color: #d4edda;
    color: #155724;
    border: 1px solid #c3e6cb;
  }
  .error {
    background-color: #f8d7da;
    color: #721c24;
    border: 1px solid #f5c6cb;
  }
  .empty {
    background-color: #d7dbf8;
    color: #143b88;
    border: 1px solid #d7dbf8;
  }
</style>




<h5>Haga click en el país para actualizar datos de la estadística</h5>

<br>

<button onclick={getInitdata}> CARGAR DATOS </button>
<button onclick={deleteCholeraStats}>BORRAR TODO</button>

<br>
<br>
<br>
<h3>FILTROS DE BÚSQUEDA</h3>
<input placeholder="País" bind:value={filterCountry} />
<input placeholder="Año" type="number" bind:value={filterYear} />
<input placeholder="Casos reportados" type="number" bind:value={filterReportedCases} />
<input placeholder="Muertes reportadas" type="number" bind:value={filterReportedDeaths} />
<input placeholder="Ratio de fatalidad" type="number" step="0.01" bind:value={filterFatalityRate} />
<input placeholder="Región" bind:value={filterRegion} />
<input placeholder="Desde" type="number" bind:value={filterFrom} />
<input placeholder="Hasta" type="number" bind:value={filterTo} />
<button onclick={getCholeraStats}>BUSCAR</button>
<button onclick={() => {
    filterCountry=''; filterYear=''; filterRegion=''; filterFrom=''; filterTo='';
    getCholeraStats();
}}>LIMPIAR FILTROS</button>

<br>
<br>
<h3>CREACIÓN DE ESTADISTICA</h3>

<div>
        <button onclick={decrementaOffset}>Anterior</button>
        <button onclick={incrementaOffset}>Siguiente</button>
</div>
<table>
    <thead>
        <tr>
            <th>Pais</th>
            <th>Año</th>
            <th>Casos reportados</th>
            <th>Muertes reportadas</th>
            <th>Ratio de fatalidad</th>
            <th>Región</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><input data-testid="countryInput" bind:value= {newCountry} /></td>
            <td><input data-testid="yearInput" type="number" bind:value= {newYear} /></td>
            <td><input data-testid="reportedCasesInput" type="number" bind:value= {newReportedCases} /></td>
            <td><input data-testid="reportedDeathsInput" type="number" bind:value= {newReportedDeaths} /></td>
            <td><input data-testid="fatalityRateInput" type="number" step="0.01" bind:value= {newFatalityRates} /></td>
            <td><input data-testid="regionInput" bind:value= {newWhoRegion} /></td>
            <td><button onclick={InsertCholeraStat}>INSERTAR</button></td>
        </tr>
        {#each cholera_stats as cholera_stat (`${cholera_stat.country}-${cholera_stat.year}`)}
            <tr data-testid="choleraRow">
                <td><a href="cholera-stats/{cholera_stat.country}/{cholera_stat.year}">{cholera_stat.country}</a></td>
                <td>{cholera_stat.year}</td>
                <td>{cholera_stat.reportedCases} </td>
                <td> {cholera_stat.reportedDeaths} </td>
                <td>{cholera_stat.fatalityRate} </td>
                <td>{cholera_stat.whoRegion}</td>
                <td><button data-testid={`${cholera_stat.country}-${cholera_stat.year}`} onclick={() => deleteCholeraStat(cholera_stat.country, cholera_stat.year)}>BORRAR</button></td>
             </tr>

        {/each}
    </tbody>
</table>



<!-- 
{#if cholera_stats.length==0}
    <p ></p>
    <div class="alert empty">
    <strong>¡VAYA!</strong> — No se encontraron estadisticas con esos campos.
    </div>
{/if}
-->
