// src/frontend-react/src/Aidsdeathsstats.jsx
import { useState, useEffect } from "react";

const BASE_API = "/api/v1/aids-deaths-stats";

const ESTADOS = {
  200: "200 - OK: La operación fue un éxito",
  201: "201 - Created: Creado correctamente",
  400: "400 - Bad Request: Incompatibilidad en los datos enviados",
  404: "404 - Not Found: El recurso no existe",
  405: "405 - Method Not Allowed: No puedes realizar esa operación",
  409: "409 - Conflict: Conflicto, ya existe en la base de datos",
  500: "500 - Internal Server Error: Error interno en el servidor",
};

const EMPTY = {
  country: "", codecountry: "", year: "",
  death_count_hiv_aids_under_5: 0,
  death_count_hiv_aids_70_plus: 0,
  death_count_hiv_aids_5_14: 0,
  death_count_hiv_aids_15_49: 0,
  death_count_hiv_aids_50_69: 0,
};

const LIMIT = 10;

export default function AidsDeathsStats() {
  const [datos, setDatos] = useState([]);
  const [status, setStatus] = useState(null);
  const [newRow, setNewRow] = useState(EMPTY);
  const [page, setPage] = useState(0);

  async function getDatos(p = page) {
    const res = await fetch(`${BASE_API}?limit=${LIMIT}&offset=${LIMIT * p}`);
    setDatos(await res.json());
  }

  useEffect(() => { getDatos(); }, [page]);

  async function loadInitial() {
    const res = await fetch(BASE_API + "/loadInitialData");
    setStatus(res.status);
    if (res.ok) getDatos();
  }

  async function add() {
    if (!newRow.country || !newRow.codecountry || !newRow.year) {
      setStatus(400); return;
    }
    const res = await fetch(BASE_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(newRow),
    });
    setStatus(res.status);
    if (res.status === 201) { setNewRow(EMPTY); getDatos(); }
  }

  async function del(code, yr) {
    if (!confirm("¿Borrar este registro?")) return;
    const res = await fetch(`${BASE_API}/${code}/${yr}`, { method: "DELETE" });
    setStatus(res.status);
    if (res.ok) getDatos();
  }

  async function delAll() {
    if (!confirm("¿Borrar TODOS los registros?")) return;
    const res = await fetch(BASE_API, { method: "DELETE" });
    setStatus(res.status);
    if (res.ok) { setPage(0); getDatos(0); }
  }

  const set = (field) => (e) =>
    setNewRow((prev) => ({ ...prev, [field]: e.target.value }));

  return (
    <div style={{ padding: 16, fontFamily: "sans-serif" }}>
      <h1>Muertes por SIDA</h1>
      <button onClick={loadInitial}>Cargar datos iniciales</button>{" "}
      <button onClick={delAll}>Borrar todo</button>

      <hr />

      <table border="1" cellPadding="4" style={{ borderCollapse: "collapse", width: "100%" }}>
        <thead>
          <tr>
            <th>País</th><th>Código</th><th>Año</th>
            <th>&lt;5</th><th>&gt;70</th><th>5–14</th><th>15–49</th><th>50–69</th>
            <th>Acción</th>
          </tr>
        </thead>
        <tbody>
          {datos.map((d) => (
            <tr key={d.codecountry + d.year} data-testid="dataRow">
              <td>{d.country}</td>
              <td>{d.codecountry}</td>
              <td>{d.year}</td>
              <td>{d.death_count_hiv_aids_under_5}</td>
              <td>{d.death_count_hiv_aids_70_plus}</td>
              <td>{d.death_count_hiv_aids_5_14}</td>
              <td>{d.death_count_hiv_aids_15_49}</td>
              <td>{d.death_count_hiv_aids_50_69}</td>
              <td>
                <button onClick={() => del(d.codecountry, d.year)}>Borrar</button>{" "}
                <button onClick={() => window.location.href = `/react/aidsDeath/${d.codecountry}/${d.year}`}>Editar</button>
              </td>
            </tr>
          ))}

          {/* FILA AÑADIR */}
          <tr>
            <td><input data-testid="paisInput"       value={newRow.country}     onChange={set("country")} placeholder="País" /></td>
            <td><input data-testid="codigoPaisInput" value={newRow.codecountry} onChange={set("codecountry")} placeholder="Código" /></td>
            <td><input data-testid="añoInput"        type="number" value={newRow.year} onChange={set("year")} placeholder="Año" /></td>
            <td><input data-testid="under5Input"     type="number" value={newRow.death_count_hiv_aids_under_5} onChange={set("death_count_hiv_aids_under_5")} /></td>
            <td><input data-testid="plus70Input"     type="number" value={newRow.death_count_hiv_aids_70_plus} onChange={set("death_count_hiv_aids_70_plus")} /></td>
            <td><input data-testid="5-14Input"       type="number" value={newRow.death_count_hiv_aids_5_14}   onChange={set("death_count_hiv_aids_5_14")} /></td>
            <td><input data-testid="15-49Input"      type="number" value={newRow.death_count_hiv_aids_15_49}  onChange={set("death_count_hiv_aids_15_49")} /></td>
            <td><input data-testid="50-69Input"      type="number" value={newRow.death_count_hiv_aids_50_69}  onChange={set("death_count_hiv_aids_50_69")} /></td>
            <td><button onClick={add}>+ Añadir</button></td>
          </tr>
        </tbody>
      </table>

      {/* PAGINACIÓN */}
      <p>
        <button onClick={() => setPage((p) => Math.max(0, p - 1))} disabled={page === 0}>← Anterior</button>{" "}
        Página {page + 1}{" "}
        <button onClick={() => setPage((p) => p + 1)} disabled={datos.length < LIMIT}>Siguiente →</button>
      </p>

      {/* CÓDIGOS DE ESTADO */}
      <hr />
      <h2>Códigos de estado</h2>
      {status && <p><strong>Último resultado:</strong> {ESTADOS[status] ?? `${status} - Respuesta desconocida`}</p>}
      
    </div>
  );
}

// src/frontend/src/routes/aids-deaths-stats/+page.svelte
<script>
	import { dev } from '$app/environment';
	import { onMount } from 'svelte';
	// @ts-ignore
	let datos = $state([]);
	let BASE_API = '/api/v1/aids-deaths-stats';
	let result = $state(0);

	let newCountry = $state('paísEjemplo');
	let newCodeCountry = $state('codigoPaísEjemplo');
	let newYear = $state(1111);
	let newDeath_count_hiv_aids_under_5 = $state(0);
	let newDeath_count_hiv_aids_70_plus = $state(0);
	let newDeath_count_hiv_aids_5_14 = $state(0);
	let newDeath_count_hiv_aids_15_49 = $state(0);
	let newDeath_count_hiv_aids_50_69 = $state(0);

	let estados={
        "200": "La operación fue un éxito",
        "201": "Creado correctamente",
        "409": "Conflicto en la base de datos, ya existen",
        "405": "No puedes realizar esa operación",
        "500": "Error interno en el servidor",
        "404": "El recurso no existe",
        "400": "Incompatibilidad en los datos enviados"
    }

	let limit = $state(10);
	let offset = $state(0);

	let filtro = $state("");
	
	function aplicarFiltro() {
    	filtro = limit != 10 ? `?limit=${limit}` : '';
    	getDatos();
	}


	if (dev) {
		BASE_API = 'http://localhost:3000' + BASE_API;
	}

	

	// @ts-ignore
	async function getDatos() {
		const res = await fetch(BASE_API+filtro, {
			method: 'GET'
		});
		const data = await res.json();
		datos = data;
	}
	// @ts-ignore
	async function deleteContact(codecountry, year) {
		if (confirm('¿Estás seguro de que quieres borrar este elemento?')) {
			console.log('DELETE: ' + codecountry + ', ' + year);
			const res = await fetch(BASE_API + `/${codecountry}/${year}`, {
				method: 'DELETE'
			});
			result = await res.status;
			if (res.status == 200) {
				getDatos();
			}
		}
	}
	async function deleteContacts() {
		if (confirm('¿Estás seguro de que quieres borrar toda la base de datos?')) {
			console.log('DELETE ALL');
			const res = await fetch(BASE_API, {
				method: 'DELETE'
			});
			result = await res.status;
			if (res.status == 200) {
				getDatos();
			}
		}
	}

	async function añadirContact() {
		console.log('INSERTE');
		let newDato = {
			country: newCountry,
			codecountry: newCodeCountry,
			year: newYear,
			death_count_hiv_aids_under_5: newDeath_count_hiv_aids_under_5,
			death_count_hiv_aids_70_plus: newDeath_count_hiv_aids_70_plus,
			death_count_hiv_aids_5_14: newDeath_count_hiv_aids_5_14,
			death_count_hiv_aids_15_49: newDeath_count_hiv_aids_15_49,
			death_count_hiv_aids_50_69: newDeath_count_hiv_aids_50_69
		};
		const res = await fetch(BASE_API, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify(newDato)
		});
		result = await res.status;
		if (res.status == 201) {
			getDatos();
		}
	}

	onMount(async () => {
		getDatos();
	});
</script>

<h1>aids-deaths-stats</h1>

<table>
	<thead>
		<tr>
			<th>País</th>
			<th>Codigo del País</th>
			<th>Año</th>
			<th>Menores de 5 años</th>
			<th>Mayores de 70 años</th>
			<th>Entre 5 y 14 años</th>
			<th>Entre 15 y 49 años</th>
			<th>Entre 50 y 69 años</th>
			<th>Acción</th>
		</tr>
	</thead>
	<tbody>
		{#each datos as dato (dato.codecountry + dato.year)}
			<tr>
				<td> {dato.country} </td>
				<td> {dato.codecountry} </td>
				<td> {dato.year} </td>
				<td> {dato.death_count_hiv_aids_under_5} </td>
				<td> {dato.death_count_hiv_aids_70_plus} </td>
				<td> {dato.death_count_hiv_aids_5_14} </td>
				<td> {dato.death_count_hiv_aids_15_49} </td>
				<td> {dato.death_count_hiv_aids_50_69} </td>
				<td
					><button
						onclick={() => {
							deleteContact(dato.codecountry, dato.year);
						}}>ELIMINAR</button
					></td
				>
				<td
					><button><a href="/aids-deaths-stats/{dato.codecountry}/{dato.year}">EDITAR</a></button
					></td
				>
			</tr>
		{/each}
		<tr>
			<td><input type="text" bind:value={newCountry} /> </td>
			<td><input type="text" bind:value={newCodeCountry} /></td>
			<td><input type="number" bind:value={newYear} /></td>
			<td><input type="number" bind:value={newDeath_count_hiv_aids_under_5} min="0" /></td>
			<td><input type="number" bind:value={newDeath_count_hiv_aids_70_plus} min="0" /></td>
			<td><input type="number" bind:value={newDeath_count_hiv_aids_5_14} min="0" /></td>
			<td><input type="number" bind:value={newDeath_count_hiv_aids_15_49} min="0" /></td>
			<td><input type="number" bind:value={newDeath_count_hiv_aids_50_69} min="0" /></td>
			<td><button onclick={añadirContact}>AÑADIR</button></td>
		</tr>
	</tbody>
</table>

{#if result != 0}
	<h4>Resultado de la operación: {estados[result]}</h4>
{/if}

<button onclick={deleteContacts}>ELIMINAR TODO</button>

<h3>Filtros: </h3>
<div class="card-limit">
  <h2>Número de datos: </h2>
  <input type="number" bind:value={limit} min="1"/>
</div>
<div class="card-offset">
  <h2>Número de datos: </h2>
  <input type="number" bind:value={offset} min="0"/>
</div>
<button onclick={aplicarFiltro}>Aplicar</button>
<style>
	td,
	th {
		padding: 10px;
	}
</style>
